### ISSUE TITLE
Evaluation error if string argument includes a comma

### ISSUE THREAD

**Issue by greek1979** [greek1979/jeval#1]
Evaluation of expression with string functions fails with ``EvaluationException`` ("Invalid use of quotes") when string argument(s) include a comma or another symbol designated as default argument delimiter. The reason for this is that splitting nested function arguments' string into individual arguments is done in a crude way by ``ArgumentTokenizer`` BEFORE each argument is passed to the nested function in question, so commas in original text cause the arguments' string to break apart in the most unexpected places.

Exception in thread "main" net.sourceforge.jeval.EvaluationException: Invalid use of quotes.
	at net.sourceforge.jeval.Evaluator.processNestedFunctions(Evaluator.java:1656)
	at net.sourceforge.jeval.Evaluator.getResult(Evaluator.java:1275)
	at net.sourceforge.jeval.Evaluator.evaluate(Evaluator.java:615)
	at net.sourceforge.jeval.Evaluator.evaluate(Evaluator.java:553)
	at net.sourceforge.jeval.Evaluator.main(Evaluator.java:1725)
Caused by: net.sourceforge.jeval.EvaluationException: Invalid use of quotes.
	at net.sourceforge.jeval.Evaluator.isExpressionString(Evaluator.java:1423)
	at net.sourceforge.jeval.Evaluator.getResult(Evaluator.java:1246)
	at net.sourceforge.jeval.Evaluator.evaluate(Evaluator.java:615)
	at net.sourceforge.jeval.Evaluator.evaluate(Evaluator.java:553)
	at net.sourceforge.jeval.Evaluator.processNestedFunctions(Evaluator.java:1654)
	... 4 more

**Comment by greek1979** [comment]
Modified ``ArgumentTokenizer`` so its constructor accepts optional ``quoteCharacter`` parameter. If quote character is supplied, then prior to splitting the input string into tokens (elements), any text sequence enclosed between paired quote characters is treated as a whole, and not parsed for parenthesis or argument delimiters (comma by default).

**Comment by greek1979** [comment]
Fixed in f55a5ac

**Comment by greek1979** [comment]
Fixed in f55a5ac
